# Generated by Django 5.2 on 2025-04-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
